analisis_sentimen/urls.py
from django.urls import path
from . import views

app_name = "sentimen"
urlpatterns = [
    path("dashboad/", views.dashboard, name="dashboard"),
    path("dataset/", views.dataset, name="dataset"),
    # path('preprocessing/', views.preprocessing, name="preprocessing"),
    # path("preprocessing1/<str:proses>/", views.preprocessing1, name="preprocessing1"),
    # path("preprocessing1/", views.preprocessing1, name="preprocessing2"),

    # path("preprocessing/<int:proces>/", views.preprocessing, name="preprocessing"),
    path("preprocessing/", views.preprocessing, name="preprocessing"),
    # path("training/", views.training, name="training"),


    path("preprocessing/stemming/", views.stemming, name="stemming"),
    path("preprocessing/stopword/", views.stopwords, name="stopword"),
    path("preprocessing/stemmed_stopword/", views.stemmed_stopwords, name="stemmed_stopword"),

    path("pengujian/", views.pengujian, name="pengujian"),
    path("prediksi/", views.prediksi, name="prediksi"),
    path("visualisasi/", views.visualisasi, name="visualisasi"),
]

mywebsite/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sentimen/', include("analisis_sentimen.urls", namespace="sentimen")),
    path('', views.index, name='login'),
]

templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>{{ title }}</title>
    <meta
      content="width=device-width, initial-scale=1.0, shrink-to-fit=no"
      name="viewport"
    />
    <link
      rel="icon"
      href="{% static 'assets/img/kaiadmin/favicon.ico' %}"
      type="image/x-icon"
    />

    <!-- Fonts and icons -->
    <script src="{% static 'assets/js/plugin/webfont/webfont.min.js' %}"></script>
    <script>
      WebFont.load({
        google: { families: ["Public Sans:300,400,500,600,700"] },
        custom: {
          families: [
            "Font Awesome 5 Solid",
            "Font Awesome 5 Regular",
            "Font Awesome 5 Brands",
            "simple-line-icons",
          ],
          urls: ["{% static 'assets/css/fonts.min.css' %}"],
        },
        active: function () {
          sessionStorage.fonts = true;
        },
      });
    </script>

    <!-- CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/plugins.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/kaiadmin.min.css' %}" />

    <!-- CSS Just for demo purpose, don't include it in your project -->
    <link rel="stylesheet" href="{% static 'assets/css/demo.css' %}" />
  </head>
  <body>
    <div class="wrapper">
      <!-- Sidebar -->
      {% include "layouts/sidebar.html" %}
      <!-- End Sidebar -->

      <d class="main-panel">
        <div class="main-header">
          <div class="main-header-logo">
            <!-- Logo Header -->
            <div class="logo-header" data-background-color="dark">
              <a href="index.html" class="logo">
              </a>
              <div class="nav-toggle">
                <button class="btn btn-toggle toggle-sidebar">
                  <i class="gg-menu-right"></i>
                </button>
                <button class="btn btn-toggle sidenav-toggler">
                  <i class="gg-menu-left"></i>
                </button>
              </div>
              <button class="topbar-toggler more">
                <i class="gg-more-vertical-alt"></i>
              </button>
            </div>
            <!-- End Logo Header -->
          </div>
          <!-- Navbar Header -->
          {% include "layouts/navbar.html" %}
          <!-- End Navbar -->
        </div>

        <!-- Content -->
         
         {% block content %}
             
         {% endblock content %}
            
         <!-- End Content -->

        <!-- Footer -->
        {% include "layouts/footer.html" %}
        <!-- End Footer -->
        
      </div>

      <!-- Custom template | don't include it in your project! -->
      
      <!-- <div class="custom-template">
        <div class="title">Settings</div>
        <div class="custom-content">
          <div class="switcher">
            <div class="switch-block">
              <h4>Logo Header</h4>
              <div class="btnSwitch">
                <button
                  type="button"
                  class="selected changeLogoHeaderColor"
                  data-color="dark"
                ></button>
                <button
                  type="button"
                  class="changeLogoHeaderColor"
                  data-color="blue"
                ></button>
                <button
                  type="button"
                  class="changeLogoHeaderColor"
                  data-color="purple"
                ></button>
                <button
                  type="button"
                  class="changeLogoHeaderColor"
                  data-color="light-blue"
                ></button>
                <button
                  type="button"
                  class="changeLogoHeaderColor"
                  data-color="green"
                ></button>
                <button
                  type="button"
                  class="changeLogoHeaderColor"
                  data-color="orange"
                ></button>
                <button
                  type="button"
                  class="changeLogoHeaderColor"
                  data-color="red"
                ></button>
                <button
                  type="button"
                  class="changeLogoHeaderColor"
                  data-color="white"
                ></button>
                <br />
                <button
                  type="button"
                  class="changeLogoHeaderColor"
                  data-color="dark2"
                ></button>
                <button
                  type="button"
                  class="changeLogoHeaderColor"
                  data-color="blue2"
                ></button>
                <button
                  type="button"
                  class="changeLogoHeaderColor"
                  data-color="purple2"
                ></button>
                <button
                  type="button"
                  class="changeLogoHeaderColor"
                  data-color="light-blue2"
                ></button>
                <button
                  type="button"
                  class="changeLogoHeaderColor"
                  data-color="green2"
                ></button>
                <button
                  type="button"
                  class="changeLogoHeaderColor"
                  data-color="orange2"
                ></button>
                <button
                  type="button"
                  class="changeLogoHeaderColor"
                  data-color="red2"
                ></button>
              </div>
            </div>
            <div class="switch-block">
              <h4>Navbar Header</h4>
              <div class="btnSwitch">
                <button
                  type="button"
                  class="changeTopBarColor"
                  data-color="dark"
                ></button>
                <button
                  type="button"
                  class="changeTopBarColor"
                  data-color="blue"
                ></button>
                <button
                  type="button"
                  class="changeTopBarColor"
                  data-color="purple"
                ></button>
                <button
                  type="button"
                  class="changeTopBarColor"
                  data-color="light-blue"
                ></button>
                <button
                  type="button"
                  class="changeTopBarColor"
                  data-color="green"
                ></button>
                <button
                  type="button"
                  class="changeTopBarColor"
                  data-color="orange"
                ></button>
                <button
                  type="button"
                  class="changeTopBarColor"
                  data-color="red"
                ></button>
                <button
                  type="button"
                  class="selected changeTopBarColor"
                  data-color="white"
                ></button>
                <br />
                <button
                  type="button"
                  class="changeTopBarColor"
                  data-color="dark2"
                ></button>
                <button
                  type="button"
                  class="changeTopBarColor"
                  data-color="blue2"
                ></button>
                <button
                  type="button"
                  class="changeTopBarColor"
                  data-color="purple2"
                ></button>
                <button
                  type="button"
                  class="changeTopBarColor"
                  data-color="light-blue2"
                ></button>
                <button
                  type="button"
                  class="changeTopBarColor"
                  data-color="green2"
                ></button>
                <button
                  type="button"
                  class="changeTopBarColor"
                  data-color="orange2"
                ></button>
                <button
                  type="button"
                  class="changeTopBarColor"
                  data-color="red2"
                ></button>
              </div>
            </div>
            <div class="switch-block">
              <h4>Sidebar</h4>
              <div class="btnSwitch">
                <button
                  type="button"
                  class="changeSideBarColor"
                  data-color="white"
                ></button>
                <button
                  type="button"
                  class="selected changeSideBarColor"
                  data-color="dark"
                ></button>
                <button
                  type="button"
                  class="changeSideBarColor"
                  data-color="dark2"
                ></button>
              </div>
            </div>
          </div>
        </div>
        <div class="custom-toggle">
          <i class="icon-settings"></i>
        </div>
      </div> -->
      
      <!-- End Custom template -->
    </div>
    <!--   Core JS Files   -->
    <script src="{% static 'assets/js/core/jquery-3.7.1.min.js' %}"></script>
    <script src="{% static 'assets/js/core/popper.min.js' %}"></script>
    <script src="{% static 'assets/js/core/bootstrap.min.js' %}"></script>

    <!-- jQuery Scrollbar -->
    <script src="{% static 'assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js' %}"></script>

    <!-- Chart JS -->
    <script src="{% static 'assets/js/plugin/chart.js/chart.min.js' %}"></script>

    <!-- jQuery Sparkline -->
    <script src="{% static 'assets/js/plugin/jquery.sparkline/jquery.sparkline.min.js' %}"></script>

    <!-- Chart Circle -->
    <script src="{% static 'assets/js/plugin/chart-circle/circles.min.js' %}"></script>

    <!-- Datatables -->
    <script src="{% static 'assets/js/plugin/datatables/datatables.min.js' %}"></script>

    <!-- Bootstrap Notify -->
    <!-- <script src="{% static 'assets/js/plugin/bootstrap-notify/bootstrap-notify.min.js' %}"></script> -->

    <!-- jQuery Vector Maps -->
    <script src="{% static 'assets/js/plugin/jsvectormap/jsvectormap.min.js' %}"></script>
    <script src="{% static 'assets/js/plugin/jsvectormap/world.js' %}"></script>

    <!-- Sweet Alert -->
    <script src="{% static 'assets/js/plugin/sweetalert/sweetalert.min.js' %}"></script>

    <!-- Kaiadmin JS -->
    <script src="{% static 'assets/js/kaiadmin.min.js' %}"></script>

    <!-- Kaiadmin DEMO methods, don't include it in your project! -->
    <script src="{% static 'assets/js/setting-demo.js' %}"></script>
    <script src="{% static 'assets/js/demo.js' %}"></script>
    
    {% block scripts %}
      
    {% endblock scripts %}
      
  </body>
</html>

templates/layouts/footer.html
{% load static %}
<footer class="footer">
    <div class="container-fluid d-flex justify-content-between">
      <div class="copyright">
        Copyright &copy; 2024 
        <a href="{% url 'sentimen:dashboard' %}">Aspek&Sentimen.</a>
        All rights reserved. 
      </div>
      <div>
        Version 0.0.1
      </div>
    </div>
  </footer>

templates/layouts/navbar.html
{% load static %}
<nav class="navbar navbar-header navbar-header-transparent navbar-expand-lg border-bottom">
    <div class="container-fluid">
        <!-- <nav class="navbar navbar-header-left navbar-expand-lg navbar-form nav-search p-0 d-none d-lg-flex">
          <div class="input-group">
            <div class="input-group-prepend">
              <button type="submit" class="btn btn-search pe-1">
                <i class="fa fa-search search-icon"></i>
              </button>
            </div>
            <input
              type="text"
              placeholder="Search ..."
              class="form-control"
            />
          </div>
        </nav> -->

        <ul class="navbar-nav topbar-nav ms-md-auto align-items-center">
          <!-- <li
            class="nav-item topbar-icon dropdown hidden-caret d-flex d-lg-none"
          >
            <a
              class="nav-link dropdown-toggle"
              data-bs-toggle="dropdown"
              href="#"
              role="button"
              aria-expanded="false"
              aria-haspopup="true"
            >
              <i class="fa fa-search"></i>
            </a>
            <ul class="dropdown-menu dropdown-search animated fadeIn">
              <form class="navbar-left navbar-form nav-search">
                <div class="input-group">
                  <input
                    type="text"
                    placeholder="Search ..."
                    class="form-control"
                  />
                </div>
              </form>
            </ul>
          </li> -->

          <li class="nav-item topbar-user dropdown hidden-caret">
            <a
              class="dropdown-toggle profile-pic"
              data-bs-toggle="dropdown"
              href="#"
              aria-expanded="false"
            >
              <div class="avatar-sm">
                <img
                  src="{% static 'assets/img/profile.jpg' %}"
                  alt="..."
                  class="avatar-img rounded-circle"
                />
                <!-- <i class="fas fa-user"></i> -->
              </div>
              <span class="profile-username">
                <span class="op-7">Hi,</span>
                <span class="fw-bold">Analyst</span>
              </span>
            </a>
            <!-- <ul class="dropdown-menu dropdown-user animated fadeIn">
              <div class="dropdown-user-scroll scrollbar-outer">
                <li>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#">Account Setting</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#">Logout</a>
                </li>
              </div>
            </ul> -->
          </li>
        </ul>
      </div>
</nav>

templates/layouts/sidebar.html
{% load static %}
<div class="sidebar sidebar-style-2" data-background-color="dark">
    <div class="sidebar-logo">
      <!-- Logo Header -->
      <div class="logo-header" data-background-color="dark">
        <!-- <a href="{% url 'sentimen:dashboard' %}" class="logo">
          <img
            src="{% static 'assets/img/kaiadmin/logo_light.svg' %}"
            alt="navbar brand"
            class="navbar-brand"
            height="20"
          />
        </a> -->
        <a href="{% url 'sentimen:dashboard' %}" class="logo">
            <h3 style="color: white;">Aspek dan <br>Sentimen</h3>
        </a>
        <div class="nav-toggle">
          <button class="btn btn-toggle toggle-sidebar">
            <i class="gg-menu-right"></i>
          </button>
          <button class="btn btn-toggle sidenav-toggler">
            <i class="gg-menu-left"></i>
          </button>
        </div>
      </div>
      <!-- End Logo Header -->
    </div>
    <div class="sidebar-wrapper scrollbar scrollbar-inner">
      <div class="sidebar-content">
        <ul class="nav nav-secondary">
          <li class="nav-item {% if request.resolver_match.url_name == 'dashboard' %}active{% endif %}">
            <a href="{% url 'sentimen:dashboard' %}">
                <i class="fas fa-home"></i>
              <p>Dashboard</p>
            </a>
          </li>

          <li class="nav-item {% if request.resolver_match.url_name == 'dataset' %}active{% endif %}">
            <a href="{% url 'sentimen:dataset' %}">
              <i class="fas fa-database"></i>
              <p>DataSet</p>
            </a>
          </li>
          <li class="nav-item {% if request.resolver_match.url_name == 'preprocessing' %}active{% endif %}">
            <a href="{% url 'sentimen:preprocessing' %}">
                <i class="fas fa-table"></i>
                <p>Preproseccing</p>
              </a>
          </li>
          <li class="nav-item  {% if request.resolver_match.url_name == 'pengujian' %}active{% endif %}">
            <a href="{% url 'sentimen:pengujian' %}">
                <i class="fas fa-vector-square"></i>
                <p>Pengujian Data</p>
              </a>
          </li>
          <li class="nav-item {% if request.resolver_match.url_name == 'visualisasi' %}active{% endif %}">
            <a href="{% url 'sentimen:visualisasi' %}">
                <i class="fas fa-chart-bar"></i>
                <p>Visualisasi Data</p>
              </a>
          </li>


        </ul>
      </div>
    </div>
  </div>