analisis_sentimen/urls.py
from django.urls import path
from . import views

app_name = "sentimen"
urlpatterns = [
    path("dashboad/", views.dashboard, name="dashboard"),
    path("dataset/", views.dataset, name="dataset"),
    # path('preprocessing/', views.preprocessing, name="preprocessing"),
    # path("preprocessing1/<str:proses>/", views.preprocessing1, name="preprocessing1"),
    # path("preprocessing1/", views.preprocessing1, name="preprocessing2"),

    # path("preprocessing/<int:proces>/", views.preprocessing, name="preprocessing"),
    path("preprocessing/", views.preprocessing, name="preprocessing"),
    # path("training/", views.training, name="training"),


    path("preprocessing/stemming/", views.stemming, name="stemming"),
    path("preprocessing/stopword/", views.stopwords, name="stopword"),
    path("preprocessing/stemmed_stopword/", views.stemmed_stopwords, name="stemmed_stopword"),

    path("pengujian/", views.pengujian, name="pengujian"),
    path("prediksi/", views.prediksi, name="prediksi"),
    path("visualisasi/", views.visualisasi, name="visualisasi"),
]

mywebsite/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sentimen/', include("analisis_sentimen.urls", namespace="sentimen")),
    path('', views.index, name='login'),
]

analisis_sentimen/models.py
from django.db import models

# Create your models here.

analisis_sentimen/forms.py
from fileinput import FileInput
from pydoc import classname
from django import forms

class UploadFileForm(forms.Form):
    data_csv = forms.FileField(
        widget= forms.FileInput(
            attrs = {
                'class':'form-control',
                'accept':'text/csv',
            }
        )
    )

class ParameterSVMForm(forms.Form):
    kernel = forms.CharField(
        widget= forms.TextInput(
            attrs={
                'class':'form-select'
            }
        )
    )
    nilai_C = forms.FloatField(
        widget= forms.NumberInput(
             attrs= {
                'class':'form-control',
                'placeholder':'Nilai C'
            }
        )
    ) 
    gamma = forms.FloatField(
        widget= forms.NumberInput(
            attrs= {
                'class':'form-control',
                'placeholder':'Gamma'
            }
        )
    )
    degree = forms.IntegerField(
        widget= forms.NumberInput(
            attrs= {
                'class':'form-control',
                'placeholder':'Degree'
            }
        )
    )

analisis_sentimen/views.py
from concurrent.futures import process
from multiprocessing import context
from pyexpat.errors import messages
from django.shortcuts import render, redirect
import pandas as pd
import io
import csv


from .forms import UploadFileForm
from .preprocessing import remove, remove_number, remove_single_char, remove_tweet_special
from .preprocessing import remove_question_marks, remove_punctuation_with_space, remove_whitespace_multiple_with_space
from .preprocessing import word_tokenize_wrapper, stemming_text ,stopwords_removal, to_string
# from .pemodelan import tf_idf

# View Dashboard
def dashboard(request):
    context = {
        'title':'Dashboard Sentimen Analisis',
    }
    return render(request, 'dashboard.html', context)

# Cleaning Data
# Preprocessing
def clean_data(request):
    return render(request, 'dataset.html')

# View Dataset
def dataset(request):
    dataset = []
    post_form = UploadFileForm(request.POST, request.FILES)
    if request.method == "POST":
        if post_form.is_valid():
            data = request.FILES["data_csv"]
            decode_file = data.read().decode('latin-1')
            io_string = io.StringIO(decode_file)
            reader = csv.reader(io_string, delimiter=',')
            for row in reader:
                dataset.append(row)

            # simpan data ke session
            request.session['dataset'] = dataset
            # return redirect('sentimen:preprocessing')
        else:
            messages.error(request, 'Data Tidak Sesuai')
    else:
        post_form = UploadFileForm(request.POST, request.FILES)

    context = {
        'title':'Dataset Sentimen Analisis',
        'data_form':post_form,
        'dataset': dataset

    }
    return render(request, 'dataset.html', context)


def dataset1(request):
    post_form = UploadFileForm(request.POST, request.FILES)
    if request.method == "POST":
        if post_form.is_valid():
            # print(post_form(request.FILES["data_csv"]))
            data_lower = (request.FILES["data_csv"]).str.lower()
            data_remove_punctuation = remove_punctuation_with_space(data_lower)
            data_remove_tweet_special = remove_tweet_special(data_remove_punctuation)
            data_remove_number = remove_number(data_remove_tweet_special)
            data_remove_whitespace = remove_whitespace_multiple_with_space(data_remove_number)
            data_remove_single_char = remove_single_char(data_remove_whitespace)
            data_remove_question_marks = remove_question_marks(data_remove_single_char)
            data_remove_text = remove(data_remove_question_marks)
            
            context = {
                'title':'Dataset Sentimen Analisis',
                'hasil_preprocessing':data_remove_text,
            }
            return render(request, 'dataset.html', context)
        else:
            messages.error(request, 'Data Tidak Sesuai')
    else:
        post_form = UploadFileForm(request.POST, request.FILES)
        
    context = {
        'title':'Dataset Sentimen Analisis',
        'data_form':post_form,
    }
    return render(request, 'dataset.html', context)

# View Preprocessing data 
# def preprocessing(request):
#     dataset = request.session.get('dataset', [])

#     dataset_hasil = [row for row in dataset]

#     context = {
#         'title':'Preprocessing Data',
#         'dataset':dataset_hasil
#     }
#     return render(request, 'preprocecing.html', context)

# View function
def preprocessing1(request, proces=None):
    dataset = request.session.get('dataset', [])

    if not dataset:
        return render(request, 'preprocecing.html', {'title': 'Preprocessing Data', 'dataset': []})

    df = pd.DataFrame(dataset[1:], columns=dataset[0])

    # Preprocessing
    df['preprocessed'] = df['Text'].str.lower()
    df['preprocessed'] = df['preprocessed'].apply(remove_punctuation_with_space)
    df['preprocessed'] = df['preprocessed'].apply(remove_tweet_special)
    df['preprocessed'] = df['preprocessed'].apply(remove_number)
    df['preprocessed'] = df['preprocessed'].apply(remove_whitespace_multiple_with_space)
    df['preprocessed'] = df['preprocessed'].apply(remove_single_char)
    df['preprocessed'] = df['preprocessed'].apply(remove_question_marks)

    # Apply 'remove' to 'Text'
    df['Text'] = df['Text'].apply(remove)
    df.sort_values("Text", inplace=True)
    df.drop_duplicates(subset="Text", keep="first", inplace=True)

    # Tokenization
    df['tweet_tokens'] = df['preprocessed'].apply(word_tokenize_wrapper)

    if proces == "1":
        # Stemming 
        df['stemmed_only'] = df['tweet_tokens'].apply(stemming_text)
        # To String
        df['stemmed_only_string'] = df['stemmed_only'].apply(to_string)

    elif proces == "2":
        # Stopword 
        df['stopword_only'] = df['preprocessed'].apply(stopwords_removal)
        # To String 
        df['stopword_only_string'] = df['stopword_only'].apply(to_string)

    elif proces == "3":
        # Stopword 
        df['stopword_only'] = df['preprocessed'].apply(stopwords_removal)
        # Stemming 
        df['stemmed_stopword'] = df['stopword_only'].apply(stemming_text)
        # To string 
        df['stemmed_stopword_string'] = df['stemmed_stopword'].apply(to_string)

    dataset_hasil = df.values.tolist()

    context = {
        'title': 'Preprocessing Data',
        'dataset': dataset_hasil
    }
    return render(request, 'preprocecing.html', context)

# Preprocessing 
def preprocessing(request):
    dataset = request.session.get('dataset', [])
    total_data = 0
    headers = []
    dataset_hasil = []
    proses_pilih= ""
    selected_value = ""

    if dataset:

        df = pd.DataFrame(dataset[1:], columns=dataset[0])

        #PREPROCESSING
        df['preprocessed'] = df['Text'].str.lower()
        df['preprocessed'] = df['preprocessed'].apply(remove_punctuation_with_space)
        df['preprocessed'] = df['preprocessed'].apply(remove_tweet_special)
        df['preprocessed'] = df['preprocessed'].apply(remove_number)
        df['preprocessed'] = df['preprocessed'].apply(remove_whitespace_multiple_with_space)
        df['preprocessed'] = df['preprocessed'].apply(remove_single_char)
        df['preprocessed'] = df['preprocessed'].apply(remove_question_marks)

        #apply 'remove' to 'Text'
        df['Text'] = df['Text'].apply(lambda x: remove(x))
        df.sort_values("Text", inplace=True)
        df.drop_duplicates(subset="Text", keep="first", inplace=True)
        # df = df.values.tolist()
        # print(df[0])

        # TOKENIZATION ???
        df['tweet_tokens'] = df['preprocessed'].apply(word_tokenize_wrapper)
        print(df.head())

        if request.method == "POST":
            selected_value = request.POST.get('value', "")
            proces = int(selected_value)
            # proces = int(request.POST.get('value',0))

            if proces == 1:
                proses_pilih = "Stemming"
                # Stemming 
                df['stemmed_only'] = df['tweet_tokens'].apply(stemming_text)
                print(df.head())

                # To String
                df['stemmed_only_string'] = df['stemmed_only'].apply(to_string)
                print(df.head())

            elif proces == 2:
                proses_pilih = "Stopwords"
                # Stopword 
                df['stopword_only'] = df['preprocessed'].apply(stopwords_removal)
                print(df.head())

                # to String 
                df['stopword_only_string'] = df['stopword_only'].apply(to_string)
                print(df.head())

            elif proces == 3:
                proses_pilih = "Stemming Stopwords"
                # Stopword 
                df['stopword_only'] = df['preprocessed'].apply(stopwords_removal)
                print(df.head())

                # Stemming 
                df['stemmed_stopword'] = df['stopword_only'].apply(stemming_text)
                print(df.head())

                # to string 
                df['stemmed_stopword_string'] = df['stemmed_stopword'].apply(to_string)
                print(df.head())
        
        total_data = len(df)
        headers = df.columns.tolist()
        print(headers)
        dataset_hasil = df.values.tolist()
        print(dataset_hasil[0])

        # simpan data ke session
        dataset_preprocessing = df.to_dict(orient='records')
        request.session['preprocessing'] = dataset_preprocessing
        # return redirect('sentimen:pengujian')

    context = {
        'title':'Preprocessing Data',
        'total':total_data,
        'preproses':proses_pilih,
        'selected_value':selected_value,
        'dataset':dataset_hasil,
        'header': headers,
    }
    return render(request, 'preprocecing.html', context)
 

# Stemming AJAH !!!
def stemming(request):
    dataset = request.session.get('dataset', [])

    # dataset_hasil = [row for row in dataset]

    if dataset:
        df = pd.DataFrame(dataset[1:], columns=dataset[0])

        #PREPROCESSING
        df['preprocessed'] = df['Text'].str.lower()
        df['preprocessed'] = df['preprocessed'].apply(remove_punctuation_with_space)
        df['preprocessed'] = df['preprocessed'].apply(remove_tweet_special)
        df['preprocessed'] = df['preprocessed'].apply(remove_number)
        df['preprocessed'] = df['preprocessed'].apply(remove_whitespace_multiple_with_space)
        df['preprocessed'] = df['preprocessed'].apply(remove_single_char)
        df['preprocessed'] = df['preprocessed'].apply(remove_question_marks)

        #apply 'remove' to 'Text'
        df['Text'] = df['Text'].apply(lambda x: remove(x))
        df.sort_values("Text", inplace=True)
        df.drop_duplicates(subset="Text", keep="first", inplace=True)
        # df = df.values.tolist()
        # print(df[0])

        # TOKENIZATION
        df['tweet_tokens'] = df['preprocessed'].apply(word_tokenize_wrapper)
        print(df.head())
        
        # Stemming 

analisis_sentimen/templates/dataset.html
{% extends "layouts/base.html" %}
{% load static %}
{% block content %}
<div class="container">
    <div class="page-inner">
      <div class="page-header">
        <h3 class="fw-bold mb-3">Daftar Dataset</h3>
        <ul class="breadcrumbs mb-3">
          <li class="nav-home">
            <a href="{% url 'sentimen:dashboard' %}">
              <i class="icon-home"></i>
            </a>
          </li>
          <li class="separator">
            <i class="icon-arrow-right"></i>
          </li>
          <li class="nav-item">
            <a href="{% url 'sentimen:dataset' %}">Dataset</a>
          </li>
        </ul>
      </div>
      <div class="row">

        <div class="col-md-12">
          <div class="card">
            <div class="card-header">
              <div class="d-flex align-items-center justify-content-between w-100">
                <h4 class="card-title">Tabel Daftar Dataset</h4>
                <div class="d-flex">
                    <button class="btn btn-primary btn-round ms-auto" data-bs-toggle="modal" data-bs-target="#addRowModal">
                        <i class="fa fa-plus"></i>
                        Upload Data
                      </button>
                      <!-- <a class="btn btn-warning btn-round ms-auto" href="#"><i class="fa fa-search"></i> Normalisasi</a> -->
                </div>
              </div>
            </div>
            <div class="card-body">
              <!-- Modal -->
              <div
                class="modal fade"
                id="addRowModal"
                tabindex="-1"
                role="dialog"
                aria-hidden="true"
              >
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header border-0">
                      <h5 class="modal-title">
                        <span class="fw-mediumbold"> Upload</span>
                        <span class="fw-light"> Data </span>
                      </h5>
                      <button
                        type="button"
                        class="close"
                        data-dismiss="modal"
                        aria-label="Close"
                      >
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      <p class="small">
                        Silahkan Upload Data Sentimen dengan format ".csv"
                      </p>
                      <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                          <div class="col-sm-12">
                            <div class="form-group">
                              <label for="{{ data_form.data_csv.id_for_label}}">Pilih Data</label>
                              {{ data_form.data_csv }}
                            </div>
                          </div>
                          <div class="modal-footer border-0">
                            <button type="submit" class="btn btn-primary">Upload</button>
                          </div>
                        </div>
                      </form>
                    </div>
                  </div>
                </div>
              </div>
              <!-- menampilkan datanya -->
              <div class="table-responsive">
                <table id="add-row" class="display table table-striped table-hover">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>Text</th>
                      <th>Layanan</th>
                      <th>Program</th>
                      <th>Sarana & Prasarana</th>
                      <th>Teknis</th>
                      <th>Sentimen</th>
                    </tr>
                  </thead>
                  <tbody>
                    
                    {% for row in dataset  %}
                      <tr>
        
                        {% for cell in row  %}
                          <td>
                            {{ cell }}
                          </td>
                        {% endfor %}
                          
                      </tr>
                    {% endfor %}
                      
                    <!-- <tr>
                      <td>1</td>
                      <td>Dukungan dari RRI sebagai pelaksana Bintang Radio Indonesia memberikan landasan yang kuat bagi Josh untuk terus mengembangkan bakatnya dan memberikan kontribusi positif dalam dunia musik Indonesiaa
                          <br>
                          <br>
                        Label Sentimen : <b>Positif</b>
                        <br>
                        Label Aspek : <b>["sarana_prasarana","program"] </b>
                    </td>
                      <td>
                        <div class="form-button-action">
                          <button
                            type="button"
                            data-bs-toggle="tooltip"
                            title=""
                            class="btn btn-link btn-warning btn-lg"
                            data-original-title="Edit Task"
                          >
                            <i class="fa fa-edit"></i>
                          </button>
                          <button
                            type="button"
                            data-bs-toggle="tooltip"
                            title=""
                            class="btn btn-link btn-danger"
                            data-original-title="Remove"
                          >
                            <i class="fa fa-trash"></i>
                          </button>
                        </div>
                      </td>
                    </tr>
                    <tr>
                      <td>2</td>
                      <td>
                        RRI tidak hanya mencari penyanyi berbakat, tetapi juga memberikan kesempatan untuk berkembang dan membangun karier di industri musik. #DanTerjadiLagiJosh

                        Label Sentimen : <b>positif</b>
                        Label Aspek : <b>["layanan","sarana_prasarana"] </b>
                      </td>
                      <td>
                        <div class="form-button-action">
                          <button
                            type="button"
                            data-bs-toggle="tooltip"
                            title=""
                            class="btn btn-link btn-warning btn-lg"
                            data-original-title="Edit Task"
                          >
                            <i class="fa fa-edit"></i>
                          </button>
                          <button
                            type="button"
                            data-bs-toggle="tooltip"
                            title=""
                            class="btn btn-link btn-danger"
                            data-original-title="Remove"
                          >
                            <i class="fa fa-trash"></i>
                          </button>
                        </div>
                      </td>
                    </tr> -->
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block scripts %}
<!-- <script>
    $(document).ready(function () {
      $("#basic-datatables").DataTable({});

      $("#add-row").DataTable({
        pageLength: 5,
      });

      var action =
        '<td> <div class="form-button-action"> <button type="button" data-bs-toggle="tooltip" title="" class="btn btn-link btn-primary btn-lg" data-original-title="Edit Task"> <i class="fa fa-edit"></i> </button> <button type="button" data-bs-toggle="tooltip" title="" class="btn btn-link btn-danger" data-original-title="Remove"> <i class="fa fa-times"></i> </button> </div> </td>';

      $("#addRowButton").click(function () {
        $("#add-row")
          .dataTable()
          .fnAddData([
            $("#addName").val(),
            $("#addPosition").val(),
            $("#addOffice").val(),
            action,
          ]);
        $("#addRowModal").modal("hide");
      });
    });
</script> -->
<script>
   $(document).ready(function () {
        $("#add-row").DataTable({
            pageLength: 10,
        });
    });
</script>
<script>
  document.getElementById("id_data_excel").addEventListener("change", function(){
    var fileName = this.value.split("\\").pop();
    var label = document.querySelector(".custom-file-label");
    label.textContent = fileName;
  })
</script>
{% endblock scripts %}
    
    

        

       
    

analisis_sentimen/templates/pengujian.html
{% extends "layouts/base.html" %}
{% load static %}

{% block content %}
<div class="container">
    <div class="page-inner">
      <div class="page-header">
        <h3 class="fw-bold mb-3">Daftar Data Pengujian</h3>
        <ul class="breadcrumbs mb-3">
          <li class="nav-home">
            <a href="{% url 'sentimen:dashboard' %}">
              <i class="icon-home"></i>
            </a>
          </li>
          <li class="separator">
            <i class="icon-arrow-right"></i>
          </li>
          <li class="nav-item">
            <a href="{% url 'sentimen:pengujian' %}">Pengujian</a>
          </li>
        </ul>
      </div>
      <div class="row">

        <div class="col-md-12">
          <div class="card">
            <div class="card-header">
              <div class="d-flex align-items-center justify-content-between w-100">
                <h4 class="card-title">Tabel Daftar Data Pengujian</h4>
                <!-- <div class="d-flex">
                    <button class="btn btn-primary btn-round ms-auto" data-bs-toggle="modal" data-bs-target="#addRowModal">
                        <i class="fa fa-plus"></i>
                        Tambah Data
                    </button>
                    <a class="btn btn-warning btn-round ms-auto" href="#"><i class="fa fa-search"></i> Normalisasi</a>
                </div> -->
                <div class="d-flex">
                  <a class="btn btn-warning btn-round ms-auto" href="{% url 'sentimen:prediksi' %}"><i class="fa fa-search"></i>  Analisis Sentimen</a>
                </div>
              </div>
            </div>
            <div class="card-body">
              <!-- Modal -->
              <!-- <div
                class="modal fade"
                id="addRowModal"
                tabindex="-1"
                role="dialog"
                aria-hidden="true"
              >
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header border-0">
                      <h5 class="modal-title">
                        <span class="fw-mediumbold"> New</span>
                        <span class="fw-light"> Row </span>
                      </h5>
                      <button
                        type="button"
                        class="close"
                        data-dismiss="modal"
                        aria-label="Close"
                      >
                        <span aria-hidden="true">&times;</span>
                      </button>
                    </div>
                    <div class="modal-body">
                      <p class="small">
                        Create a new row using this form, make sure you
                        fill them all
                      </p>
                      <form>
                        <div class="row">
                          <div class="col-sm-12">
                            <div class="form-group form-group-default">
                              <label>ID</label>
                              <input
                                id="addid"
                                type="text"
                                class="form-control"
                                placeholder="Id"
                              />
                            </div>
                          </div>
                          <div class="col-md-12 pe-0">
                            <div class="form-group form-group-default">
                              <label>Text & Aspek</label>
                              <input
                                id="text_aspek"
                                type="text"
                                class="form-control"
                                placeholder="Text & Aspek"
                              />
                            </div>
                          </div>
                        </div>
                      </form>
                    </div>
                    <div class="modal-footer border-0">
                      <button
                        type="button"
                        id="addRowButton"
                        class="btn btn-primary"
                      >
                        Tambah
                      </button>
                      <button
                        type="button"
                        class="btn btn-danger"
                        data-dismiss="modal"
                      >
                        Kembali
                      </button>
                    </div>
                  </div>
                </div>
              </div> -->

              <div class="table-responsive">
                <table
                  id="pengujian-table"
                  class="display table table-striped table-hover"
                >
                  <thead>
                    <tr>
                      {% for column in header  %}
                        <th>{{ column }}</th>
                      {% endfor %}
                    </tr>
                  </thead>
                  <tbody>
                    {% for row in dataset  %}
                      <tr>
                        
                        {% for cell in row  %}
                          <td>{{ cell }}</td>
                        {% endfor %}
                          
                    </tr>
                    {% endfor %}
                    <!-- <tr>
                      <td>1</td>
                      <td>Dukungan dari RRI sebagai pelaksana Bintang Radio Indonesia memberikan landasan yang kuat bagi Josh untuk terus mengembangkan bakatnya dan memberikan kontribusi positif dalam dunia musik Indonesiaa
                          <br>
                          <br>
                        Label Sentimen : <b>Positif</b>
                        <br>
                        Label Aspek : <b>["sarana_prasarana","program"] </b>
                    </td>
                      <td>
                        <div class="form-button-action">
                          <button
                            type="button"
                            data-bs-toggle="tooltip"
                            title=""
                            class="btn btn-link btn-warning btn-lg"
                            data-original-title="Edit Task"
                          >
                            <i class="fa fa-edit"></i>
                          </button>
                          <button
                            type="button"
                            data-bs-toggle="tooltip"
                            title=""
                            class="btn btn-link btn-danger"
                            data-original-title="Remove"
                          >
                            <i class="fa fa-trash"></i>
                          </button>
                        </div>
                      </td>
                    </tr>
                    <tr>
                      <td>2</td>
                      <td>
                        RRI tidak hanya mencari penyanyi berbakat, tetapi juga memberikan kesempatan untuk berkembang dan membangun karier di industri musik. #DanTerjadiLagiJosh

                        Label Sentimen : <b>positif</b>
                        Label Aspek : <b>["layanan","sarana_prasarana"] </b>
                      </td>
                      <td>
                        <div class="form-button-action">
                          <button
                            type="button"
                            data-bs-toggle="tooltip"
                            title=""
                            class="btn btn-link btn-warning btn-lg"
                            data-original-title="Edit Task"
                          >
                            <i class="fa fa-edit"></i>
                          </button>
                          <button
                            type="button"
                            data-bs-toggle="tooltip"
                            title=""
                            class="btn btn-link btn-danger"
                            data-original-title="Remove"
                          >
                            <i class="fa fa-trash"></i>
                          </button>
                        </div>
                      </td>
                    </tr> -->
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block scripts %}
<script>
  $(document).ready(function () {
    // Add Row
    $("#pengujian-table").DataTable({
      pageLength: 5,
    });

  });
</script>
{% endblock scripts %}
    